$background = rgb({{colors.background.default.hex_stripped}})
$foreground = rgb({{colors.on_background.default.hex_stripped}})
$primary = rgb({{colors.primary.default.hex_stripped}})
$on_primary = rgb({{colors.on_primary.default.hex_stripped}})
$surface_container = rgb({{colors.surface_container.default.hex_stripped}})
$outline = rgb({{colors.outline.default.hex_stripped}})
